apiVersion: v1
kind: Service
metadata:
  name: {{ include "juice-shop.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "juice-shop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "juice-shop.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
